[[main]]
    identifier = "games"
    name = "Games"
    url = "/games/"
    weight = 10
[[main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 20

[[icons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/DaltonSW"
    weight = 10
[[icons]]
    identifier = "steam"
    name = "Steam"
    url = "https://steamcommunity.com/id/daltonsw"
    weight = 20
[[icons]]
    identifier = "itch"
    name = "Itch"
    url = "https://daltonsw.itch.io/"
    weight = 30
[[icons]]
    identifier = "telegram"
    name = "Telegram"
    url = "https://t.me/daltonsw"
    weight = 40
[[icons]]
    identifier = "email"
    name = "Email"
    url = "mailto:email@dalton.dog"
    weight = 50
