[[main]]
    identifer = "projects"
    name = "Projects"
    url = "/projects/"
    weight = 10
[[main]]
    identifier = "game-jams"
    name = "Game Jams"
    url = "/game-jams"
    weight = 11
# [[main]]
#     identifer = "favorites"
#     name = "Favorites"
#     url = "/favorites/"

[[icons]]
    identifier = "github"
    name = "GitHub"
    url = "https://github.com/DaltonSW"
    weight = 10
[[icons]]
    identifier = "email"
    name = "Email"
    url = "mailto:email@dalton.dog"
    weight = 1
[[icons]]
    identifier = "steam"
    name = "Steam"
    url = "https://steamcommunity.com/id/daltonsw"
    weight = 30
[[icons]]
    identifier = "telegram"
    name = "Telegram"
    url = "https://t.me/daltonsw"
    weight = 15
[[icons]]
    identifier = "itch"
    name = "Itch"
    url = "https://daltonsw.itch.io/"
    weight = 20
