author = "Dalton Williams"
description = "Dalton's Web Place"

showPostsLink = false # Show 'Posts' link in the header 
showSinglePageAsHome = true # Gives a bespoke home page instead of auto-rendered
homeSinglePage = "/home.md" # 'Works well with extraContentDirs', per README
extraContentDirs = ["thoughts"]

# It's best to put these icons in the "static" folder of your site
logo = "/logo.svg"
favicon = "/favicon.png"  # 32x32
faviconIco = "/favicon.ico"  # 32x32
appletouch = "/apple-touch-icon.png"  # 180x180
svgicon = "/logo.svg"
icon512 = "/icon512.png"  # 512x512 png image

logoRightOfTitle = true
showTags = false
# showRss = true

# imageInArticlePreview = false  # show images in article preview; default false
# fitImageInArticlePreview = false  # make article preview images fit the article preview instead of getting cropped
# articleSummary = true  # show a summary in article preview; default true


#NOTE: To use custom fonts with Ficurinia, load the CSS file in /layouts/partials/inject/head.html
fontFamily = "SauceCodePro NF"  # changes the font, default "JetBrains Mono"
titleFontFamily = "MartianMono NF"  # font used for titles and headings
monospaceFontFamily = "MartianMono NF"  # changes the monospace font for code, default "JetBrains Mono"

# multipliers applied to font sizes
titleFontSizeMultiplier = 0.9
mainFontSizeMultiplier = 1.1
monoFontSizeMultiplier = 1.1

# contentWidth = "1000px"  # maximum width of the site content, css syntax

paperCards = true  # enable paper card style; default false
# buttonTags = true  # enable button tag style; default false
# tagsInArticlePreview = true  # enable tags list in the article preview card
gridView = false  # show post list as a grid. goes well with paperCards
bigArticleTitle = false  # makes the title in the single article view bigger
# navtype = "standard"  # changes the style of the pagination, available styles are: "standard", "circles"
# enableShadow = false  # shows a shadow around some elements
menuStyle = "buttons"  # changes the style of the main site navigation menu, available styles are: "standard", "buttons"
# inputStyle = "standard" # changes the style of inputs (like the searchbar), available styles are: "standard", "buttons"

# enableSearch = false  # enable search page
# searchbarEverywhere = true  # if the searchbar should be shown in every page; requires enableSearch
# searchMenuLink = false  # add a search link to the navigation menu; requires enableSearch
# mobileHamburgerNav = false  # alternative hamburger menu layout for the main nav menu when screen is small

# enableFeatured = true  # enable a particular view for articles marked as featured (featured: true in the article frontmatter)
underlineTitleLinks = true  # show an underline also for links that are titles
tocBeforeImage = true  # show the table of contents before the main article image; default false
 
enableSidebarLayout = true
tocInSidebar = true  # if the sidebar is enbabled, show the TOC in the sidebar
 
  # redirect to baseURL if current URL host doesn't match
  # useful if deploying in gitlab pages with custom domain and don't want
  # the username.gitlab.io/website url to persist
  # this requires you to set baseURL (see above)
  # forceRedirect = false

  # NOTE: you need to enable JSON output for this to work!
  #   look at the [outputs] section below

  # infiniteScrolling = false  # activates infinite scrolling instead of regular pagination

  # enableFooterColumns = false  # activates footer columns, configured in data/footer_columns.yml
  # enableJumbotron = false  # enables jumbotron, data/jumbotron.yml

  # related articles will be selected randomly based on tags and shown at
  # the bottom of the article, after the comments
  # enableRelatedArticles = false
  # relatedArticlesNum = 2  # how many related articles to show
  # randomRelated = false  # sorts related articles in random order (randomized at build time)
